# Generated by Django 2.2.5 on 2019-09-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalplant',
            name='ramping_rate_BSE_MW',
            field=models.FloatField(default=0, verbose_name='Ramping Rate BSE [MW/time]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='ramping_rate_NRM_MW',
            field=models.FloatField(default=0, verbose_name='Ramping Rate NRM [MW/time]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='ramping_rate_RMP_MW',
            field=models.FloatField(default=0, verbose_name='Ramping Rate RMP [MW/time]'),
            preserve_default=False,
        ),
    ]
