# Generated by Django 2.2.5 on 2019-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_auto_20190917_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalplant',
            name='DW_cost',
            field=models.FloatField(default=0, verbose_name='DW_cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='MEL',
            field=models.FloatField(default=0, verbose_name='Maximal export limit [MW]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='MIN',
            field=models.FloatField(default=0, verbose_name='Minimal export limit [MW]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='SEL',
            field=models.FloatField(default=0, verbose_name='Stable export limit [MW]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='UPcold_cost',
            field=models.FloatField(default=0, verbose_name='UPcold_cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='UPhot_cost',
            field=models.FloatField(default=0, verbose_name='UPhot_cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='UPhot_time',
            field=models.FloatField(default=0, verbose_name='UPhot_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='UPwarm_cost',
            field=models.FloatField(default=0, verbose_name='UPwarm_cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='UPwarm_time',
            field=models.FloatField(default=0, verbose_name='UPwarm_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='consumption',
            field=models.FloatField(default=0, verbose_name='Consumption/Input [MW]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='depreciation_MW',
            field=models.FloatField(default=0, verbose_name='Depreciation of ??? [EUR/MW]'),
            preserve_default=False,
        ),
    ]
