# Generated by Django 2.2.5 on 2019-09-17 14:48

import dispatch.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_auto_20190917_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', dispatch.fields.CompressedJSONField()),
            ],
        ),
    ]
