# Generated by Django 2.2.5 on 2019-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_auto_20190917_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='unit',
            field=models.CharField(default='', max_length=124),
        ),
        migrations.AlterField(
            model_name='timeseriesindex',
            name='index_type',
            field=models.IntegerField(choices=[(1, 'integer'), (2, 'datetime')], default=1),
        ),
    ]
