# Generated by Django 2.2.5 on 2019-09-25 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_auto_20190923_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalplant',
            name='last_altered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='name',
            field=models.CharField(default='Plant', max_length=256, verbose_name='Plant name'),
        ),
        migrations.AddField(
            model_name='thermalplant',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thermalplant',
            name='depreciation',
            field=models.FloatField(verbose_name='Depreciation [EUR/MW]'),
        ),
    ]
