# Generated by Django 2.2.5 on 2019-09-26 10:17

import dispatch.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0011_auto_20190925_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileupload',
            name='file',
            field=models.FileField(upload_to=dispatch.models.unique_filename_user_directory, validators=[dispatch.models.csv_validator], verbose_name='Time series CSV'),
        ),
        migrations.AlterField(
            model_name='thermalplant',
            name='capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacity [MW]'),
        ),
        migrations.AlterField(
            model_name='thermalplant',
            name='efficiency',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Efficiency [0-1]'),
        ),
        migrations.CreateModel(
            name='ThermalPlantOptimizationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('simulation_time', models.IntegerField(null=True, verbose_name='Simulation time [s]')),
                ('start', models.IntegerField(null=True, verbose_name='Offset for optimization run.')),
                ('end', models.IntegerField(null=True, verbose_name='End of optimization run.')),
                ('number_of_batches', models.IntegerField(null=True, verbose_name='Number of batches.')),
                ('overlap', models.FloatField(null=True, verbose_name='Overlap between batches.')),
                ('dispatch_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.ThermalPlantDispatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThermalPlantOptimizationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.ThermalPlantOptimizationRun')),
            ],
        ),
    ]
