# Generated by Django 2.2.5 on 2019-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_auto_20190926_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalplantoptimizationresult',
            name='consumption',
            field=models.FloatField(default=0, verbose_name='Consumption [MWh]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplantoptimizationresult',
            name='fuel_price',
            field=models.FloatField(default=0, verbose_name='Clean fuel price [EUR/MWh]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplantoptimizationresult',
            name='power_price',
            field=models.FloatField(default=0, verbose_name='Wholesale power price [EUR/MWh]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplantoptimizationresult',
            name='production',
            field=models.FloatField(default=0, verbose_name='Production [MWh]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermalplantoptimizationresult',
            name='ramping_BSE',
            field=models.FloatField(default=0, verbose_name='Production during BSE ramping [MWh]'),
            preserve_default=False,
        ),
    ]
